# Generated by Django 5.2.8 on 2025-11-07 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.member'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
