# Generated by Django 5.2.8 on 2025-11-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approved by admin?'),
        ),
    ]
