# Generated by Django 5.2.8 on 2025-11-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_trainer_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="admin_approved",
            field=models.BooleanField(default=False),
        ),
    ]
